apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: posts-api
  name: posts-api
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: posts-api
    spec:
      containers:
      - env:
        - name: GET_HOSTS_FROM
          value: dns
        image: paltamadura/posts-api-go:v1
        name: posts-api-go-api
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /go/src/posts-api-go
          name: posts-api-claim0
      hostname: posts-api-go-api
      restartPolicy: Always
      volumes:
      - name: posts-api-claim0
        persistentVolumeClaim:
          claimName: posts-api-claim0
status: {}
